env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      VITE_SUPABASE_URL: ${{secrets.SUPABASE_URL}}
      VITE_SUPABASE_PUBLIC_KEY: ${{secrets.SUPABASE_ANON_KEY}}
      VITE_PORT: ${{secrets.PORT}}
      SUPABASE_URL: ${{secrets.SUPABASE_URL}}
      SUPABASE_ANON_KEY: ${{secrets.SUPABASE_ANON_KEY}}
      SUPABASE_SERVICE_KEY: ${{secrets.SUPABASE_SERVICE_KEY}}
      PORT: ${{secrets.PORT}}
      TEST_USER_EMAIL: ${{secrets.TEST_USER_EMAIL}}
      TEST_USER_PW: ${{secrets.TEST_USER_PW}}
      AUTH_TEST_EMAIL: ${{secrets.AUTH_TEST_EMAIL}}
      AUTH_TEST_PW: ${{secrets.AUTH_TEST_PW}}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: Install front-end dependencies
      run: npm install
      working-directory: ./

    - name: Install back-end dependencies
      run: npm install
      working-directory: ./service-api

    - name: Install playwright browsers
      run: npx playwright install --with-deps
      working-directory: ./

    - name: Run backend tests (jest)
      run: npm test
      working-directory: ./service-api
    
    - name: Run frontend Integration tests (Vitest)
      run: npm run test:integration
      working-directory: ./
    
    - name: Run frontend E2E tests (playwright)
      run: npm run test:e2e
      working-directory: ./
